### ISSUE TITLE
256 Color Games do not rip Sprites Properly

### ISSUE THREAD

**Issue by Sunlitspace542** [LAK132/SourceExplorer#10]
When I rip gfx from 256 color games, or lower color level games, the graphics are all messed up.
![400](https://user-images.githubusercontent.com/35207254/58431256-f36ec880-807a-11e9-9cf4-59a8110c61e3.png) should look like this 
![429](https://user-images.githubusercontent.com/35207254/58431266-fcf83080-807a-11e9-86ce-82e95a18c174.png) rips like this

**Comment by LAK132** [comment]
I have finally got SE to be able to tell what objects/images are on a frame, so we should be able to get colour palettes for 256 colour images very soon

**Comment by LAK132** [comment]
Fixed in the latest release
