### ISSUE TITLE
image dumping issue still not fixed

### ISSUE THREAD

**Issue by Sunlitspace542** [LAK132/SourceExplorer#11]
![image](https://user-images.githubusercontent.com/35207254/59161481-1eacdb00-8ab1-11e9-9765-e0ab8dc4d845.png)
the image dumper still doesn't dump correctly with sorted dumps or normal image dumping.

**Comment by LAK132** [comment]
Any chance you could send me this game?

**Comment by Sunlitspace542** [comment]
yes I can

**Comment by Sunlitspace542** [comment]
[pacguy.zip](https://github.com/LAK132/SourceExplorer/files/3270114/pacguy.zip)
here

**Comment by Sunlitspace542** [comment]
also it's not just with this game
other games i have rip weird like this too

**Comment by LAK132** [comment]
Fixed in e2abc10
