### ISSUE TITLE
why are all the shaders encrypted

### ISSUE THREAD

**Issue by justbasicisaaccase** [LAK132/SourceExplorer#110]
### Describe the bug

every time I decompile a game and look in the shaders folder, every file says something like this: DXBCO3·‡½4deÐ‘Ë<G
if I try to put it into clickteam it doesnt work. am I doing something wrong? 

### Crash log

[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/11363518/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)
(the crash log isnt very helpful)

**Comment by REDxEYE** [comment]
These are compiled directX shaders, they are not encrypted. Currently there is no tools that can decompile then into original code

**Comment by justbasicisaaccase** [comment]
oh ok
