### ISSUE TITLE
Slow processing

### ISSUE THREAD

**Issue by Loliboly** [LAK132/SourceExplorer#113]
Maybe i am missing something. I mean i am not mad at all that the program is slow. Maybe by design. But i want it to be faster. I don't care how high up the CPU usage will jump. Maybe make an option available for the user to make the program use all resources that it needs. Should my CPU get to 100% then so be it. Sorry for posting this as an issue but i am new to github. Thanks for the attention!

**Comment by LAK132** [comment]
Loading games still needs work to multithread, however if you're just concerned with the dump speed, there's an option in the `Compatibility` menu to enable multithreading. Enabling this will make the log files unreadable, but that's only an issue if SE runs into a problem.

**Comment by Loliboly** [comment]
It works. I had to download v2.1.3 Didn't know that was a thing
