### ISSUE TITLE
Title for MMF1 games do not appear

### ISSUE THREAD

**Issue by plaindinks** [LAK132/SourceExplorer#12]
The titles for these games appear in previous builds but do not appear in the new builds.

**Comment by plaindinks** [comment]
Old
![image](https://user-images.githubusercontent.com/25271085/59162994-8b7f9f80-8ac8-11e9-9083-14eccc82796f.png)
 
New

**Comment by LAK132** [comment]
Can you show me the Entry Information tab for that one please

**Comment by plaindinks** [comment]
![image](https://user-images.githubusercontent.com/25271085/59166832-aae3f000-8afb-11e9-8dcd-6d668ce58209.png)
![image](https://user-images.githubusercontent.com/25271085/59166843-bd5e2980-8afb-11e9-9e06-392cb0553f7b.png)
It only appears in the memory explorer.

**Comment by LAK132** [comment]
Fixed in e2abc10
