### ISSUE TITLE
I can't get sprites from OWAF Extended Demo

### ISSUE THREAD

**Issue by gamorBux** [LAK132/SourceExplorer#124]
Game Download Link:
https://gamejolt.com/get/build?game=166765&build=1307736

### Describe the bug

It's unable to export a images of this game.

### Crash log

[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/12642181/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)
in V.2.1.1

**Comment by LAK132** [comment]
Works in v2.1.9
