### ISSUE TITLE
I can not get sprites from POPGOES 2016

### ISSUE THREAD

**Issue by gamorBux** [LAK132/SourceExplorer#125]
Game Download Link:
https://gamejolt.com/get/build?game=579945&build=1091222

### Describe the bug

it's unable to extract the sprites from this game

### Crash log

[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/12642207/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)
In V.2.1.1

**Comment by LAK132** [comment]
Appears to work in v2.1.9
