### ISSUE TITLE
An error about failing to inflate when ripping from .ccn files

### ISSUE THREAD

**Issue by ThatOneNetBattler** [LAK132/SourceExplorer#126]
### Describe the bug

So I've been trying to rip the soundtrack from the non-Steam/itchio release of Treasure Hunter Man (http://www.origamihero.com/thm.zip), but for some reason this version specifically is giving me an error. I also get this error with a different game, Stargirl and the Thief from the Exploded Moon (http://www.origamihero.com/stargirl.zip). I have no idea what's so special about these two games that have them be unrippable.

### Crash log

[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/12774474/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)

**Comment by LAK132** [comment]
Will be fixed in v2.1.10
