### ISSUE TITLE
Dormitabis Remastered Crashing dump

### ISSUE THREAD

**Issue by Soldiervscout** [LAK132/SourceExplorer#127]
### Describe the bug

Crashes newer version of Source but doest work for older versions

### Crash log

DEBUG [90m(../src/main.cpp:209)[0m: Graphics: 0x2
LoadGame [90m(../src/explorer.cpp:62)[0m
{
| DEBUG [90m(../src/explorer.cpp:64)[0m: Attempting To Load "C:\\Users\\atmlk\\Downloads\\dormitabis-remastered.exe"
| reserve failed: 0x0

**Comment by Soldiervscout** [comment]
Newer version being betas and older being the stable release

**Comment by LAK132** [comment]
Please upload the log file, not part of the text from it

**Comment by LAK132** [comment]
Probably fixed in v.2.1.9
