### ISSUE TITLE
Source Explorer fails to process UNDERTALE: Last Breath Renewed by Cracked Wolf

### ISSUE THREAD

**Issue by githubfan125** [LAK132/SourceExplorer#128]
### Game download link

https://gamejolt.com/games/UndertaleLasBreathRenewed/588386

### Crash log

[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/13065344/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)

**Comment by LAK132** [comment]
Fixed in v2.1.9
