### ISSUE TITLE
Error when it starts to dump game.

### ISSUE THREAD

**Issue by ViolettSmith** [LAK132/SourceExplorer#129]
### Describe the bug

1. Game used https://gamejolt.com/games/UCN/348047
2. Open srcexp.exe
3. File > Open and Dump... > [Game directory] > customnight.exe > open
4. Fully loads
5. Then it should get a error at 4% while dumping

### Crash log

[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/13110374/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)

**Comment by LAK132** [comment]
Fixed in v2.1.9
