### ISSUE TITLE
Source Explorer fails to process >Dormitabis 

### ISSUE THREAD

**Issue by SubzeroCatalyst** [LAK132/SourceExplorer#130]
### Game download link

https://gamejolt.com/games/Dormitabis/108410

### Crash log

[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/13196983/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)

**Comment by LAK132** [comment]
Partially fixed in 2.1.7

**Comment by LAK132** [comment]
Fixed in v2.1.9
