### ISSUE TITLE
Source Explorer fail to process Oblitus Casa 2.0 & Can't save the Error log

### ISSUE THREAD

**Issue by baldi233** [LAK132/SourceExplorer#131]
### Describe the bug

Game Download Link : https://gamejolt.com/games/OblitusCasa/356260

1. Open srcexp.exe
2. Drag the game file to SourceExplorer window
3. The error log appears and can't process
4. Try to save the Error log
5. When click the "Save Error Log" , programs get stuck and exit automatically

### Crash log

Can't save the Error log.

Here's the screenshot：

![2023-10-29 143259](https://github.com/LAK132/SourceExplorer/assets/124134387/e5812327-2671-48ae-9b9c-115d102cfed0)

**Comment by LAK132** [comment]
2.1.5 was broken, can you try again with 2.1.6? And make sure your debug menu looks like this before opening a game if it causes a crash
![image](https://github.com/LAK132/SourceExplorer/assets/1386467/170cd1cb-6391-4b9b-a6a9-7f26c399802b)

**Comment by baldi233** [comment]
save Error log works now, but still fails to process the game.

![image](https://github.com/LAK132/SourceExplorer/assets/124134387/e7962803-d307-4266-b30a-7dd21225e0e6)

[Errorlog.txt](https://github.com/LAK132/SourceExplorer/files/13197736/Errorlog.txt)

**Comment by LAK132** [comment]
Fixed in v2.1.9
