### ISSUE TITLE
advise the king v1.1.0 has out of data errors and attempt fails

### ISSUE THREAD

**Issue by ZePezant** [LAK132/SourceExplorer#134]
### Game download link

https://lionarc.itch.io/advise-the-king

### Crash log

[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/13542265/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)

**Comment by AITYunivers** [comment]
The game is made in GameMaker Studio, not Clickteam Fusion.
