### ISSUE TITLE
Source Explorer fails to process Final Nights 4

### ISSUE THREAD

**Issue by MohdNancy** [LAK132/SourceExplorer#135]
### Game download link

https://gamejolt.com/games/FinalNights4/267878

### Crash log

[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/13900923/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)

**Comment by LAK132** [comment]
UE4 isn't supported
