### ISSUE TITLE
Source Explorer fails to process [One Night At Flumpty's 3]

### ISSUE THREAD

**Issue by AronGamer890** [LAK132/SourceExplorer#136]
### Game download link

https://gamejolt.com/games/onaf3/529078

### Crash log

Source Explorer x86_64 v2.2.0-a6a87e2
DEBUG [90m(../src/main.cpp:236)[0m: Graphics: OpenGL
DEBUG [90m(D:\a\SourceExplorer\SourceExplorer\src\main_window.hpp:44)[0m: Open And Dump
DEBUG [90m(../subprojects/lak/src/imgui/widgets.cpp:361)[0m: [34mparsed_filter.first.size()[0m: 0x2
DEBUG [90m(../subprojects/lak/src/imgui/widgets.cpp:364)[0m: [34mname, ext[0m: CTF, *.exe;*.ccn;*.dat;*.gam;*.ugh
DEBUG [90m(../subprojects/lak/src/imgui/widgets.cpp:364)[0m: [34mname, ext[0m: All Files, *.*
LoadGame() [90m(../src/ctf/explorer.cpp:67)[0m
{
| DEBUG [90m(../src/ctf/explorer.cpp:69)[0m: Attempting To Load "C:\\Program Files (x86)\\One Night at Flumpty's 3\\ONAF3.exe"
| DEBUG [90m(../src/ctf/explorer.cpp:86)[0m: File Size: 0x648E00
| ParsePEHeader() [90m(../src/ctf/explorer.cpp:260)[0m
| {
| : DEBUG [90m(../src/ctf/explorer.cpp:263)[0m: EXE Signature: 0x5A4D
| : DEBUG [90m(../src/ctf/explorer.cpp:275)[0m: EXE Pointer: 0x120, At: 0x3C
| : DEBUG [90m(../src/ctf/explorer.cpp:278)[0m: PE Signature: 0x4550
| : DEBUG [90m(../src/ctf/explorer.cpp:291)[0m: Number Of Header Sections: 0x6
| : DEBUG [90m(../src/ctf/explorer.cpp:298)[0m: Pos: 0x218
| : Section 0x1/0x6 [90m(../src/ctf/explorer.cpp:303)[0m
| : {
| : | DEBUG [90m(../src/ctf/explorer.cpp:305)[0m: Start: 0x218
| : | ParseImageSectionHeader() [90m(../src/ctf/explorer.cpp:246)[0m
| : | {
| : | }
| : | DEBUG [90m(../src/ctf/explorer.cpp:309)[0m: Name: .text
| : | DEBUG [90m(../src/ctf/explorer.cpp:310)[0m: Size: 0x439A00
| : | DEBUG [90m(../src/ctf/explorer.cpp:311)[0m: Addr: 0x400
| : }
| : Section 0x2/0x6 [90m(../src/ctf/explorer.cpp:303)[0m
| : {
| : | DEBUG [90m(../src/ctf/explorer.cpp:305)[0m: Start: 0x240
| : | ParseImageSectionHeader() [90m(../src/ctf/explorer.cpp:246)[0m
| : | {
| : | }
| : | DEBUG [90m(../src/ctf/explorer.cpp:309)[0m: Name: .rdata
| : | DEBUG [90m(../src/ctf/explorer.cpp:310)[0m: Size: 0x106C00
| : | DEBUG [90m(../src/ctf/explorer.cpp:311)[0m: Addr: 0x439E00
| : }
| : Section 0x3/0x6 [90m(../src/ctf/explorer.cpp:303)[0m
| : {
| : | DEBUG [90m(../src/ctf/explorer.cpp:305)[0m: Start: 0x268
| : | ParseImageSectionHeader() [90m(../src/ctf/explorer.cpp:246)[0m
| : | {
| : | }
| : | DEBUG [90m(../src/ctf/explorer.cpp:309)[0m: Name: .data
| : | DEBUG [90m(../src/ctf/explorer.cpp:310)[0m: Size: 0x8A200
| : | DEBUG [90m(../src/ctf/explorer.cpp:311)[0m: Addr: 0x540A00
| : }
| : Section 0x4/0x6 [90m(../src/ctf/explorer.cpp:303)[0m
| : {
| : | DEBUG [90m(../src/ctf/explorer.cpp:305)[0m: Start: 0x290
| : | ParseImageSectionHeader() [90m(../src/ctf/explorer.cpp:246)[0m
| : | {
| : | }
| : | DEBUG [90m(../src/ctf/explorer.cpp:309)[0m: Name: .mydata
| : | DEBUG [90m(../src/ctf/explorer.cpp:310)[0m: Size: 0x200
| : | DEBUG [90m(../src/ctf/explorer.cpp:311)[0m: Addr: 0x5CAC00
| : }
| : Section 0x5/0x6 [90m(../src/ctf/explorer.cpp:303)[0m
| : {
| : | DEBUG [90m(../src/ctf/explorer.cpp:305)[0m: Start: 0x2B8
| : | ParseImageSectionHeader() [90m(../src/ctf/explorer.cpp:246)[0m
| : | {
| : | }
| : | DEBUG [90m(../src/ctf/explorer.cpp:309)[0m: Name: .rsrc
| : | DEBUG [90m(../src/ctf/explorer.cpp:310)[0m: Size: 0x4C400
| : | DEBUG [90m(../src/ctf/explorer.cpp:311)[0m: Addr: 0x5CAE00
| : }
| : Section 0x6/0x6 [90m(../src/ctf/explorer.cpp:303)[0m
| : {
| : | DEBUG [90m(../src/ctf/explorer.cpp:305)[0m: Start: 0x2E0
| : | ParseImageSectionHeader() [90m(../src/ctf/explorer.cpp:246)[0m
| : | {
| : | }
| : | DEBUG [90m(../src/ctf/explorer.cpp:309)[0m: Name: .reloc
| : | DEBUG [90m(../src/ctf/explorer.cpp:310)[0m: Size: 0x31C00
| : | DEBUG [90m(../src/ctf/explorer.cpp:311)[0m: Addr: 0x617200
| : }
| : DEBUG [90m(../src/ctf/explorer.cpp:318)[0m: Jumping To: 0x648E00
| }
| DEBUG [90m(../src/ctf/explorer.cpp:101)[0m: Successfully Parsed PE Header
| ParseGameHeader() [90m(../src/ctf/explorer.cpp:329)[0m
| {
| : DEBUG [90m(../src/ctf/explorer.cpp:333)[0m: Pos: 0x648E00
| }
}
[91m[1mERROR [0m[90m(../src/dump.cpp:858)[0m: AttemptExe failed: 0x2: No game header. If this game has an associated .DAT file, open that instead.
at [90m(../src/dump.cpp:94:36)[0m: struct lak::result<struct lak::result<struct lak::monostate,struct lak::stack_trace>,enum lak::await_error> __cdecl SourceExplorer::OpenGame(struct SourceExplorer::source_explorer_t &):
	OpenGame
at [90m(../src/ctf/explorer.cpp:125:3)[0m: struct lak::result<struct lak::monostate,struct lak::stack_trace> __cdecl SourceExplorer::LoadGame(struct SourceExplorer::source_explorer_t &):
	LoadGame: while parsing game header at: 0x648E00
at [90m(../src/ctf/explorer.cpp:339:6)[0m: struct lak::result<struct lak::monostate,struct lak::stack_trace> __cdecl SourceExplorer::ParseGameHeader(struct SourceExplorer::data_reader_t &,struct SourceExplorer::game_t &,bool)
DEBUG [90m(D:\a\SourceExplorer\SourceExplorer\src\main_window.hpp:100)[0m: Save Error Log

pls someone

**Comment by LAK132** [comment]
This was made in game maker, not ctf
