### ISSUE TITLE
[Enhancement] export older MMF1 games to project file (TGF/MMF1 .gam, .cca, KNP .gam, .img, .snd)

### ISSUE THREAD

**Issue by Sunlitspace542** [LAK132/SourceExplorer#14]
Being able to export older MMF1 games to a project file would be nice. Especially with the really old MMF1 games that I've been dumping.

**Comment by LAK132** [comment]
Source Explorer is not a decompiler. 
This feature request would be better suited for [Anaconda](https://github.com/LAK132/anaconda)
