### ISSUE TITLE
bug with open sorce

### ISSUE THREAD

**Issue by LuigiRulez2022** [LAK132/SourceExplorer#142]
[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/14552731/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)
[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/14552734/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)

**Comment by LAK132** [comment]
Please provide the rest of the details as required by the issue template

**Comment by LuigiRulez2022** [comment]
sorry for the late update its fnaf 2 open source will not open with this sorry
