### ISSUE TITLE
gl_invalid_enum error

### ISSUE THREAD

**Issue by czctus** [LAK132/SourceExplorer#148]
My friend is unable to start Source Explorer. The application fails to launch and produces an error message.

**Screenshots**
![image](https://github.com/user-attachments/assets/19214ce7-cd91-4bb8-8cd1-dea99863aacc)
(username was hidden since the person im submitting this issue for doesnt want it shown.)

**Launch directory**
What directory did you attempt to start Source Explorer in?
C:\Users\User\srcexp

**Desktop:**
 - OS: Windows 10
 - Graphics card: Intel(R) HD Graphics

**Additional context**
They downloaded 2.2.0 64x from the Releases, ran srcexp.exe, however it didnt start. I told them to run it via command prompt and it said:
```
FATAL (../subprojects/lak/src/imgui/backend.cpp:1009): unwrap failed: GL_INVALID_ENUM (0x500)
Something went wrong!
Saving crash log to 'Something went wrong!
Saving crash log to '
```
No crash log was created

**Comment by LAK132** [comment]
try launching with `--nogl` (`srcexp.exe --nogl`)

**Comment by czctus** [comment]
thank you, my friend said the --nogl option fixed the startup issue.
