### ISSUE TITLE
Start Up Error

### ISSUE THREAD

**Issue by skylerknott1846** [LAK132/SourceExplorer#17]
Everytime I Try To Open Source Explorer I Get These Errors
![Screenshot (16)](https://user-images.githubusercontent.com/54250152/63230652-b7f91b80-c1dd-11e9-8ca5-7a25d85f67dc.png)
![Screenshot (15)](https://user-images.githubusercontent.com/54250152/63230653-b7f91b80-c1dd-11e9-945e-1ee75bf40412.png)
And The Source Explorer Shuts Down

**Comment by REDxEYE** [comment]
https://www.microsoft.com/en-US/download/details.aspx?id=53840 install Visual C++ 2015 Redistributable
