### ISSUE TITLE
Crashing with non-ASCII character in file path

### ISSUE THREAD

**Issue by EcoleKeine** [LAK132/SourceExplorer#19]

**Comment by LAK132** [comment]
Can you give me an example?

**Comment by RostislavGames** [comment]
I have the same issue. It even gives an "Assertion Failed" error.
I have Intel Core i5 processor, Windows 7, Intel HD 3000 and 4 GB of RAM. Is something wrong there?

**Comment by RostislavGames** [comment]
Same as for the old versions.

**Comment by LAK132** [comment]
ok, so once again can you please ***give me an example of a directory that causes this crash***. I can't help you if you don't help me help you.

**Comment by RostislavGames** [comment]
Ok. I tried to start at C:\Users\Rostislav\Downloads\Source.Explorer.v0.2.4\x64 folder.

**Comment by LAK132** [comment]
You don't have any non-ASCII characters in that path. You have a completely different issue. Please open a new issue with a screenshot of the assertion failure and whatever else you can get from the console window.

**Comment by REDxEYE** [comment]
@RostislavGames Напиши еще путь к игре которую ты пытаешься открыть и путь из которого запускаешь SE

**Comment by EcoleKeine** [comment]
@LAK132 
> Can you give me an example?
I do some try , and sorry , it crash because a file have a "・"(U+30FB) character, in Windows 7 Simplified Chinese Ver.

**Comment by LAK132** [comment]
Thank you! It appears that I've managed to accidentally fix this issue at some point since the last release. I'll package up a new version with this fix tonight. Stay tuned!
