### ISSUE TITLE
Assertion Failure on Startup

### ISSUE THREAD

**Issue by RostislavGames** [LAK132/SourceExplorer#20]
![dwm_ysgUVa7Op1](https://user-images.githubusercontent.com/56727290/67098184-5e54a380-f1c4-11e9-99e0-7e54b23e4b79.png)
This error on the console appeared when I tried to start the program as I said on the previous issue. I have Visual C++ 2005-2019 installed.

**Comment by LAK132** [comment]
Sorry, you need a computer that can handle at least OpenGL 3.2 to run Source Explorer.

**Comment by LAK132** [comment]
Latest build has a software render callback, give it a try

**Comment by RostislavGames** [comment]
Now it worked. Thank you so much!
