### ISSUE TITLE
Assertion failed: g13wInit<> == GL3W_OK, file D:\Repos/SourceExplorer\src\lak.cpp, line 113

### ISSUE THREAD

**Issue by gingeyboi** [LAK132/SourceExplorer#21]
Help?

**Comment by gingeyboi** [comment]
Still does not work.

**Comment by LAK132** [comment]
It's almost like nothing has changed. ***Wait for the next update***

**Comment by gingeyboi** [comment]
Everyone else has gotten it to work perfectly, I don't see how I need to wait for the next update, seems like kinda like just a shoved in promotion. My computer does not support OpenGL.

**Comment by LAK132** [comment]
***It doesn't work for anyone with a computer that doesn't support OpenGL 3.2, and it never has***

**Comment by LAK132** [comment]
Latest build has a software render callback, give it a try
