### ISSUE TITLE
Please make OpenGL 2.0-3.0 support

### ISSUE THREAD

**Issue by OWER396** [LAK132/SourceExplorer#23]
Please add OpenGL 2.0-3.0 support

**Comment by LAK132** [comment]
My 2012 ThinkPad has OpenGL 3.3, what the hell kinda shitbox are you using?

**Comment by LAK132** [comment]
Regardless, no. But I'll do #24

**Comment by OWER396** [comment]
> My 2012 ThinkPad has OpenGL 3.3, what the hell kinda shitbox are you using?

Shitty laptop (2 GB ram, no GPU, Celeron T3100) from dafucking 2009

**Comment by LAK132** [comment]
Latest build has a software render callback, give it a try

**Comment by OWER396** [comment]
> Latest build has a software render callback, give it a try

after school. (i have ideapad G550 btw ;-;

**Comment by OWER396** [comment]
> Latest build has a software render callback, give it a try

Still not working

**Comment by LAK132** [comment]
If you don't explain how it's not work I can't bloody help you. Can you film it with a phone or some shit?

**Comment by LAK132** [comment]
Give v1.1.1 a whirl

**Comment by OWER396** [comment]
> Give v1.1.1 a whirl

i've just woke up but ok

**Comment by OWER396** [comment]
> Give v1.1.1 a whirl

O SHIT IT WORKS, THANK YOU VERY MUCH BRO

**Comment by OWER396** [comment]
> Give v1.1.1 a whirl

Tried to dump some game and it also worked, thank you <3

**Comment by OWER396** [comment]
> Give v1.1.1 a whirl

btw do u have discord?
