### ISSUE TITLE
So basically, I was trying out a new game to decomiple

### ISSUE THREAD

**Issue by DormNes** [LAK132/SourceExplorer#25]
The bug was like, it gives me the sounds, icon, binary stuff and shaders, but not once does it give me the image, I did it both sorted and unsorted but when  I did it unsorted, all the images appeared, but! it was all static

I honestly don't know what's wrong, all I know that its doing its job, but the images are fucked for a lack of better words

![image](https://user-images.githubusercontent.com/60552763/73597468-5530dd80-44fa-11ea-934b-6081c3fa9b3a.png)
 it looks like this

**Comment by LAK132** [comment]
I can't help you without
1. The name of the game 
2. The Source Explorer log file

**Comment by DormNes** [comment]
ah, okay well its Maniac Mania, and where do I go for the log file?

**Comment by LAK132** [comment]
File > Save Debug Log (or something, I don't remember off the top of my head). Make sure you save it *after* trying to dump the images.

**Comment by DormNes** [comment]
gotcha

**Comment by DormNes** [comment]
Hang do, you mean Error Log?

**Comment by LAK132** [comment]
Debug, Error, all the same. It's the only log option in there. Also, please upload it to Pastebin

**Comment by DormNes** [comment]
https://pastebin.com/Bj7tdse3 so this I guess

**Comment by DormNes** [comment]
So, um.. did you work it? Like. Just want an update on the situation.

**Comment by LAK132** [comment]
Software issues can take days/weeks/months to fix, please be patient

**Comment by DormNes** [comment]
Ah, wunderbar. I just wanted to check in is all. But, sorry for the inconvenience if you will.

**Comment by LAK132** [comment]
Sorry, looks like this game was recompiled with something like Anaconda, games like this cannot be opened with Source Explorer currently as we have no idea how the engine works.

**Comment by DormNes** [comment]
Well that is an oof.  Sorry to hear that. Though I do hope that does get sorted out.

**Comment by LAK132** [comment]
Anaconda/Chowdren is a faster engine for games with in Fusion.

**Comment by DormNes** [comment]
ah alright, again hope you figure out how the engine work. have a good day/night. whatever your timezone is

**Comment by SmilerFurcifer** [comment]
So why you trying to extract my game dorm hmm? I thought you didn't like it.
