### ISSUE TITLE
Image Dumping Error.

### ISSUE THREAD

**Issue by spook2** [LAK132/SourceExplorer#29]
The game I was dumping: Jollibee's Phase 2 By IvanG.
I first tried to auto-dump, after SE finished auto-dumping, I couldn't find the images, so I tried to dump the images myself, The images are all just noise.
https://i.redd.it/qnrwjjjsmfs41.png < Extra proof that all textures is noise.
So you can help me, I made a pastebin for the console.
Here's the link: https://pastebin.com/VhDGRYFD
I hope you can find a way to help me, thank you.

**Comment by LAK132** [comment]
Noted as #34
