### ISSUE TITLE
Ability to dump sound or other files

### ISSUE THREAD

**Issue by DeStilleGast** [LAK132/SourceExplorer#3]
There is a function to dump images, why not the ability to dump sound files (or any file with a click of a button)

**Comment by LAK132** [comment]
These features have been added, they just haven't been made public yet.

**Comment by DeStilleGast** [comment]
Awesome, but if I may ask, why isn't in released yet ?
(or is it just made a few days/weeks ago)

**Comment by LAK132** [comment]
We're in the process of rewriting SE from scratch, the rewrite isn't finished yet
