### ISSUE TITLE
Tried to dump images from a game.

### ISSUE THREAD

**Issue by JadSchm** [LAK132/SourceExplorer#32]
Hello. I tried to dump images from FNaS: Maniac Mania. But the images for some reason are replaced by static. I don't know, what's the reason, but i hope that's it will be fixed.
Here's the error log: [SEND-THIS-CRASH-LOG-TO-LAK132.txt](https://github.com/LAK132/SourceExplorer/files/4707289/SEND-THIS-CRASH-LOG-TO-LAK132.txt)

Well, i tried to dump the demo version, but i need the full version images. All of the parameters are compatible, but the images are don't for unknown reason.

Also, i got all except for images, so that's it.
Here's screenshot, what i've got:
![image](https://user-images.githubusercontent.com/66198553/83347549-ef414f00-a34f-11ea-83b7-2d3108862889.png)

So, i hope that the new version of SE will fix that issue. Thanks!

**Comment by LAK132** [comment]
Noted as #34
