### ISSUE TITLE
HELP! I can't dump

### ISSUE THREAD

**Issue by Lucoshi** [LAK132/SourceExplorer#33]
Hello. I tried to dump images from Ultra Custom Night and Fnaf World Redacted. But the images for some reason are replaced by static. I don't know, what's the reason, but i hope that's it will be fixed. I can't rip Here's the error logs: [Ultra Custom Night](https://github.com/LAK132/SourceExplorer/files/4876531/Ultra.Custom.Night.SEND-THIS-CRASH-LOG-TO-LAK132.txt) Neither [Fnaf World Redacted](https://github.com/LAK132/SourceExplorer/files/4876537/FnafWorldSEND-THIS-CRASH-LOG-TO-LAK132.txt)

**Comment by LAK132** [comment]
Noted as #34
