### ISSUE TITLE
Crashing Issues

### ISSUE THREAD

**Issue by BenProductions** [LAK132/SourceExplorer#4]
when i try to run Source explorer.
it crashes,even on the old versions
i don't know what to do

**Comment by LAK132** [comment]
Is it crashing at start up or while pulling apart a game? 
If the latter, launch Source Explorer from the command prompt and redirect the log output to a file
```
C:\path\to\sourcexplorer\> sourcexplorer.exe > dump.txt
```
Then upload the dump.txt to pastebin and share it here

**Comment by BenProductions** [comment]
it is crashing at start up

**Comment by LAK132** [comment]
Hmm.. See if you can try saving a log out anyway

**Comment by BenProductions** [comment]
ok

**Comment by BenProductions** [comment]
i followed the steps and the dump.txt file and there's nothing on it

**Comment by BenProductions** [comment]
maybe the source explorer doesn't work on windows 7

**Comment by LAK132** [comment]
Does anything come up in the console if you don't add the `> dump.txt` part? `Assertion failed: gl3wInit() == GL3W_OK` by chance?

**Comment by BenProductions** [comment]
nothing appears.
I guess it doesn't work on windows 7

**Comment by BenProductions** [comment]
since i tested on a windows 10 and it worked fine

**Comment by BenProductions** [comment]
i guess you should add support to windows 7 users

**Comment by LAK132** [comment]
It works perfectly fine on Windows 7, it's your computer specifically that it's having issues with. What are the specs or brand/model of you machine?

**Comment by BenProductions** [comment]
The PC i use is Samsung model
unfortunately,the PC's battery burned so it only works with the charger.
So rn i can't check which model is it

**Comment by gingeyboi** [comment]
How do you add the dump.txt part? Whenver I open the game it does say assertion failed at the beggining.

**Comment by LAK132** [comment]
@gingeyboi I already closed #21, please wait for the next update.

**Comment by LAK132** [comment]
No update in almost 12 months. Feel free to reopen if you work out what model computer it is that is having issues.
