### ISSUE TITLE
Toad Strike Back: mojibake file system error 

### ISSUE THREAD

**Issue by p0008874** [LAK132/SourceExplorer#40]
[SEND-THIS-CRASH-LOG-TO-LAK132.txt](https://github.com/LAK132/SourceExplorer/files/5647300/SEND-THIS-CRASH-LOG-TO-LAK132.txt)

**Comment by LAK132** [comment]
3 questions:
1. Is your computer set to use English?
2. Were you using auto-dump mode?
3. Have you tried saving the images to a different folder?

**Comment by LAK132** [comment]
closing until more information is provided

**Comment by p0008874** [comment]
> 3 questions:
> 
> 1. Is your computer set to use English?
> 2. Were you using auto-dump mode?
> 3. Have you tried saving the images to a different folder?

1.No
2.Yes
3.No

**Comment by p0008874** [comment]
Also it getting worst on latest version.
[SEND-THIS-CRASH-LOG-TO-LAK132.txt](https://github.com/LAK132/SourceExplorer/files/6719596/SEND-THIS-CRASH-LOG-TO-LAK132.txt)
