### ISSUE TITLE
Images don't dump correctly or even at all even if the game is Clickteam Fusion

### ISSUE THREAD

**Issue by PumpkinScare** [LAK132/SourceExplorer#41]
# IMPORTANT
Please provide a copy of the Error Log (File -> Save Error Log...) or the Crash Log ("SEND-THIS-CRASH-LOG-TO-LAK132.txt") uploaded to https://pastebin.com . Without this we cannot/will not help you! 

**Describe the bug**
Basically, I was dumping a Fangame, it dumped the sound files correctly, etc. But the images did not. The game I encountered this bug was from "Five Nights At Treasure Island - 2020 [Offical]". Other people have had the same problem on different games.

**To Reproduce**
There is no reproduce as it could be random games. However, I could tell you to encounter this error is to download "Five Nights At Treasure Island - 2020 [Offical]" from Gamejolt and try to dump the images.

**Expected behavior**
I expected everything to work correctly and get my sound effects, images, and bonus files. 

**Screenshots**
https://gyazo.com/7fb17ba11d9f0c99a1814135f901accd
3 errors I encountered while dumping.

**Additional context**
I could be completely wrong, and this isn't a ClickTeam Fusion Game, but it dumps the sound files correctly. This could just be a misunderstanding, but I thought it would be nice to share it here.

![image](https://user-images.githubusercontent.com/72858036/101821454-f793f700-3af5-11eb-9549-0bc4904b8bbc.png)

**Comment by PumpkinScare** [comment]
If anyone does want the link to the game, be my guest.
https://gamejolt.com/games/treasureislandofficial/222994

**Comment by LAK132** [comment]
Please follow the instructions and up load the entire log. This looks to be a common issue so I'm linking it to #43

**Comment by denraillo** [comment]
And How To Solve This Problem?

**Comment by LAK132** [comment]
@denraillo wait for #43 to be addressed

**Comment by denraillo** [comment]
I realized that games on the clickteam 2.5 + engine need to reset the Textures
