### ISSUE TITLE
Invalid Game Header Issue

### ISSUE THREAD

**Issue by JustaNewUser** [LAK132/SourceExplorer#44]
Recently downloaded SourceExplorer, i must say you're a GODSEND to whoever made this, many thanks.

To the actual issue, i tested it out on an .EXE file/game and it works, But not always.
In another .exe file, it doesn't extract the files and says "Invalid Game Header".
Source Explorer starts up and extracts just fine, but it seems that some .exe files don't have a valid header, it seems.
I'd appreciate the help if anyone could fix the issue.

[SEND-THIS-CRASH-LOG-TO-LAK132.txt](https://github.com/LAK132/SourceExplorer/files/5706552/SEND-THIS-CRASH-LOG-TO-LAK132.txt)

(If no one can open the .txt file, here's most of it, no hurries though, i can wait)

DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:41): Loading Game
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:48): File Size: 0xa0ae1e9
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:173): Parsing PE header
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:176): EXE Signature: 0x5a4d
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:187): EXE Pointer: 0x100, At: 0x3c
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:190): PE Signature: 0x4550
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:201): Number Of Header Sections: 9
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:208): Pos: 0x1f8
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:215): Name: .text
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:233): Pos: 0x220
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:215): Name: .itext
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:233): Pos: 0x248
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:215): Name: .data
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:233): Pos: 0x270
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:215): Name: .bss
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:233): Pos: 0x298
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:215): Name: .idata
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:233): Pos: 0x2c0
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:215): Name: .tls
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:233): Pos: 0x2e8
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:215): Name: .rdata
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:233): Pos: 0x310
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:215): Name: .reloc
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:233): Pos: 0x338
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:215): Name: .rsrc
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:227): Size: 0x38600
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:228): Addr: 0x1a8a00
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:240): First Short: 0xc5a0
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:243): PAME Magic: 0x121ac5a0
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:246): Pack Magic: 0x36f8d9a2121ac5a0
DEBUG(D:\Repos\SourceExplorer\src\explorer.cpp:248): Pos: 0x1e1000
ERROR(D:\Repos\SourceExplorer\src\explorer.cpp:279): Invalid Game Header
ERROR(D:\Repos\SourceExplorer\src\explorer.cpp:55): Error 'Invalid Game Header' While Parsing PE Header, At: 0x1e1000

**Comment by JustaNewUser** [comment]
Also, not sure if it's a bug or not. Please forgive me if i posted this in the wrong place. Thanks.

**Comment by JustaNewUser** [comment]
Also, not sure if this is the right place to post this.
Please forgive me if i posted this in the wrong place. Thanks.

**Comment by LAK132** [comment]
`Invalid Game Header` normally means the game you're trying to open wasn't made with Clickteam Fusion. If you're certain that it was, please let me know what game it is so I can take a look at it myself.

**Comment by JustaNewUser** [comment]
Alright, Thanks for responding.
Game was made in GameMaker so that seems to be the issue.

Thanks for the help.

Also, if SourceExplorer is still being updated, just one question: do you plan on making one for Games made on GameMaker.
Just a question, no one is forcing you to do it, but there's my suggestion.

**Comment by piratesephiroth** [comment]
> 
> 
> Alright, Thanks for responding.
> Game was made in GameMaker so that seems to be the issue.
> 
> Thanks for the help.
> 
> Also, if SourceExplorer is still being updated, just one question: do you plan on making one for Games made on GameMaker.
> Just a question, no one is forcing you to do it, but there's my suggestion.

try UndertaleModTool for that

**Comment by JustaNewUser** [comment]
Alright, Thanks for the Info.
