### ISSUE TITLE
Failed To Inflate: Corrupt Stream

### ISSUE THREAD

**Issue by stunnindude** [LAK132/SourceExplorer#45]
# IMPORTANT
Please provide a copy of the Error Log (File -> Save Error Log...) or the Crash Log ("SEND-THIS-CRASH-LOG-TO-LAK132.txt") uploaded to https://pastebin.com . Without this we cannot/will not help you! 

**Describe the bug**
I tried to open "Five Nights at Candy's 3, but it glitched out and everything was empty.

[SEND-THIS-CRASH-LOG-TO-LAK132.txt](https://github.com/LAK132/SourceExplorer/files/5743611/SEND-THIS-CRASH-LOG-TO-LAK132.txt)

**Screenshots**

**Additional context**

**Comment by LAK132** [comment]
Same error as #30
