### ISSUE TITLE
Images for dumping won't appear (sounds still dump properly)

### ISSUE THREAD

**Issue by MattWarkoski** [LAK132/SourceExplorer#46]
# IMPORTANT
Please provide a copy of the Error Log (File -> Save Error Log...) or the Crash Log ("SEND-THIS-CRASH-LOG-TO-LAK132.txt") uploaded to https://pastebin.com . Without this we cannot/will not help you! 

**Describe the bug**
Before I address the bug, I just wanted to point out that this ONLY happened to a specific game I was attempting to dump (the game was a Clickteam Fusion Application Runtime, and the name of the game is Animator's Hell)
Now, the bug in question is that everything except the images of the game will not dump. Things like the sounds and even some effects stuff is dumped (despite some audio not playing due to unsupported formats, but honestly, I'm not worried about that). I used auto-dump because dumping images manually won't work for this game. A folder for images was even created, but nothing appeared. I'm sure I know why this is happening, but I'm sure it's just because SE hasn't been optimized with these kinds of applications yet.

**To Reproduce**
1. Go to 'Desktop > Games > FNaF Games > Animator's Hell.exe'
2. Click on 'Open'
3. Wait for the decompiling to finish
4. See error (no images dumped into image folder.

**Expected behavior**
I expected, as per usual, the images to dump, considering the dump itself was loading. I was then expecting the images to go to the images folder and be there.

**Screenshots**

**Additional context**
Like I said before, I'm fairly certain I know why this is happening (the application is a Clickteam Application Runtime, and SE simply hasn't been optimized for the application yet) but it's acts fairly similar to a regular standalone application. Other than that, I haven't experienced any other issues with the dumper (the newest version actually fixed a previous issue I had where a different kind of application made on Clickteam wouldn't dump properly). Awaiting the next version of SE, excited to see the future of it!

Also, here is the crash log: 
[SEND-THIS-CRASH-LOG-TO-LAK132.txt](https://github.com/LAK132/SourceExplorer/files/5790061/SEND-THIS-CRASH-LOG-TO-LAK132.txt)

**Comment by LAK132** [comment]
Thank you for reporting. This issue is being tracked as #43
