### ISSUE TITLE
A Game With A Kitty 2: Darkside Adventures

### ISSUE THREAD

**Issue by P-Star7** [LAK132/SourceExplorer#51]
Error Log: [https://pastebin.com/djcXvpc9](url)

The game!
[http://www.caiman.us/scripts/fw/f2697.html](url)

Expected behavior: Something! But nothing happens after I open this .exe (either in auto-dump mode or manual dump mode) besides a few errors popping up in the terminal window. I'm running it in admin mode on a 64-bit system, BTW - shouldn't be any issues with that part.

**Comment by LAK132** [comment]
this has now been fixed, thanks for the report. please wait for the next release.

side note: if didn't already know, you will need to open the `.ugh` files as well as the `.exe` in source explorer to get all of the data from this game.

**Comment by P-Star7** [comment]
Thanks, updated to 2.0.1 and it dumps great! Thanks for the tip on unzipping the launcher .exe. The music didn't dump when doing an auto-dump (it was kind of a big one and I forgot to save the error log, so I'll only do THAT again if this doesn't work), so I'm trying to just load the .ugh and dump the music. When I load the game (works!) and click "Dump Music", I'm presented with "Open Folder". What exactly am I supposed to be selecting, here? Clicking on a folder (or entering the path to one and pressing Enter) just takes me there.

**Comment by LAK132** [comment]
Once you have navigated to the folder, there should be an "Open" button at the bottom. When you click Open, it will save all of the data into that folder.

**Comment by P-Star7** [comment]
Ah, it appears now. I wonder if I had forgotten to run Source Explorer as an administrator? Anyways, I can indeed do what you said to myapp.ugh, but I get a "No Music Bank" error. The same applies to all the other .ugh files. Here is the crash log, as performed using the x64 version as an administrator when opening myapp.ugh and "saving" the music to a folder. I'm sorry in advance, but it's so big that I had to .zip up the .txt file instead of using Pastebin - trying to paste it it just made the page hang in Chrome.
[SEND-THIS-CRASH-LOG-TO-LAK132.zip](https://github.com/LAK132/SourceExplorer/files/6588386/SEND-THIS-CRASH-LOG-TO-LAK132.zip)

**Comment by LAK132** [comment]
I'll take a look later. In the mean time, make sure to try saving sounds instead of music (they are different things in this engine)

**Comment by P-Star7** [comment]
> I'll take a look later. In the mean time, make sure to try saving sounds instead of music (they are different things in this engine)

Oh yeah, it saved some .wav sounds, but the music is specifically MIDI.

**Comment by P-Star7** [comment]
2.0.2 didn't seem to do anything differently in regards to the "no music bank" error, and I can confirm that individually choosing to dump the sounds just results in the usual sound effects without any MIDIs.

**Comment by LAK132** [comment]
As far as I can tell Source Explorer is actually saving the MIDI files, it's just saving them as `.wav` for some reason. All of the "Darkside" files in `myapp.ugh` are MIDIs.

**Comment by LAK132** [comment]
Update: they're tracker modules not midis.

**Comment by P-Star7** [comment]
Thank you. Where are these being saved, for you? Please take a screenshot of your folder structure when you auto-dump myapp.ugh and point out where I should be looking.

**Comment by LAK132** [comment]
`myapp/sounds/*.xm` 
![image](https://user-images.githubusercontent.com/1386467/122692773-17129600-d276-11eb-8c1d-1599fcafe6b2.png)

**Comment by LAK132** [comment]
(should be) fixed in v2.0.3
