### ISSUE TITLE
Not dumping 2.5+ images

### ISSUE THREAD

**Issue by ahaijka56** [LAK132/SourceExplorer#52]
I tried to dump files of sonicallstars.exe but program dumped only sounds,icon,and effects

Log:
[allstars.txt](https://github.com/LAK132/SourceExplorer/files/6583827/allstars.txt)

**Comment by LAK132** [comment]
Was this using the latest stable release or did you build SE yourself?

**Comment by ahaijka56** [comment]
latest relase

**Comment by ahaijka56** [comment]
i downloaded 2.0 but program crashes

**Comment by LAK132** [comment]
In that case this is a duplicate of #43
