### ISSUE TITLE
Gui Glitch

### ISSUE THREAD

**Issue by ahaijka56** [LAK132/SourceExplorer#53]
Gui has a glitch when i tried open select menu
Screenshot:
![image](https://user-images.githubusercontent.com/20770102/120508003-e6b7a480-c3f9-11eb-9212-551bc71eff55.png)

**Comment by LAK132** [comment]
Does launching source explorer from the command line with the -nogl flag still have this problem?
![image](https://user-images.githubusercontent.com/1386467/123081985-b5148500-d45d-11eb-8c98-7251c7223aa6.png)

**Comment by ahaijka56** [comment]
no, thanks
