### ISSUE TITLE
I Can't Get The Game Files

### ISSUE THREAD

**Issue by denraillo** [LAK132/SourceExplorer#54]
# IMPORTANT
Please provide a copy of the Error Log (File -> Save Error Log...) or the Crash Log ("SEND-THIS-CRASH-LOG-TO-LAK132.txt") uploaded to https://pastebin.com . Without this we cannot/will not help you! 
[SEND-THIS-CRASH-LOG-TO-LAK132.txt](https://github.com/LAK132/SourceExplorer/files/6602413/SEND-THIS-CRASH-LOG-TO-LAK132.txt)

**Describe the bug**
I Wanted To get Pictures From The Game 
FNaTreasure Island 2020 But They Don't
reset Version SE 2.0.2

**Screenshots**
![image](https://user-images.githubusercontent.com/84269321/120888493-3916e200-c601-11eb-8c9e-7b9a923dbf96.png)
![image](https://user-images.githubusercontent.com/84269321/120888504-4633d100-c601-11eb-845e-6796cc5afeed.png)

**Additional context**
I'm Russian :)

**Comment by LAK132** [comment]
closing until log file is provided

**Comment by denraillo** [comment]
[Uploading SEND-THIS-CRASH-LOG-TO-LAK132.txt…]()

**Comment by denraillo** [comment]
I edited the post and you can download the file there

**Comment by denraillo** [comment]
I added a log with errors to the post

**Comment by denraillo** [comment]
> closing until log file is provided

I added a log with errors to the post
