### ISSUE TITLE
It won't dump FNaF: Open Source

### ISSUE THREAD

**Issue by CrazyPhoenixproductions** [LAK132/SourceExplorer#58]
So I've been having an issue with the program and it is that it won't dump FNaF: OP, for more information on the matter, all I know is that the game was made in GM2 (Game maker studio 2). When I try to dump the files, it just gets stuck on 0% for pretty much all the time. Which is telling me it isn't working at all, or at least for this game, not only that but it crashes with other games too. So is there any way to fix this?

**Comment by davidsotelo424** [comment]
This tool was made ONLY to dump Clickteam Fusion, not Game Maker or any other engine.
