### ISSUE TITLE
Error reading entry 6

### ISSUE THREAD

**Issue by Flusak1235** [LAK132/SourceExplorer#6]
i tried to decompile a non-fnaf game made with fusion and this popped up in the console, i got no images,sounds at all

**Comment by REDxEYE** [comment]
Hello! Can you provide game executable file?

**Comment by Flusak1235** [comment]
> Hello! Can you provide game executable file?

the exe file is too big

**Comment by REDxEYE** [comment]
Use any filehosting, e.g OneDrieve, Google Drive, DropBox and etc

**Comment by Flusak1235** [comment]
> DropBox

yeah, the game is some neo-nazi shitpost, the icon is offensive, do you really want it?

**Comment by REDxEYE** [comment]
Yes, we need to find out why it causes errors in SourceExplorer

**Comment by Flusak1235** [comment]
> Yes, we need to find out why it causes errors in SourceExplorer

mk, lemme upload it on dropbox, gonna take like an hour

**Comment by Flusak1235** [comment]
> Yes, we need to find out why it causes errors in SourceExplorer

https://www.dropbox.com/s/nd6ub152cd6exp0/AngryGoy.exe?dl=0

**Comment by REDxEYE** [comment]
They have something weird in frame chunks, my own decompiler managed to read executable, but failed at reading events. Though, disabling event loading fixed everything

**Comment by Flusak1235** [comment]
> They have something weird in frame chunks, my own decompiler managed to read executable, but failed at reading events. Though, disabling event loading fixed everything

would it be possible for you to send me the decompiler or the PNG files? thanks
