### ISSUE TITLE
A bit of a question but

### ISSUE THREAD

**Issue by BurgerMeister777** [LAK132/SourceExplorer#62]
I'm very new to this whole compilation ordeal. I followed all the steps up to the one running setup.bat, and for some reason the setup.bat requires a 'vcvarsall.bat directory'. I pointed it to my directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvarsall.bat.

It then says it can't find vcvarsall.bat when I pointed it directly towards vcvarsall.bat. Any help here? I'm probably making a very idiotic mistake somewhere but like I said I'm very very new to this business. Removing the 'vcvarsall.bat' part from the directory just caused the whole thing to close. Maybe I'm pointing it towards a wrong bat file?

Also something to keep in mind is that I'm using the latest version of the full rewrite.

**Comment by LAK132** [comment]
when it asked for the vcvarsall.bat, did you put it in quotes? `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvarsall.bat"`? I'll add the Professional version to the list of automatically tested paths

**Comment by LAK132** [comment]
d161b90baa66bda9b95112f7b6741e815765f70d should have it auto detect your version of msvc

**Comment by BurgerMeister777** [comment]
I didn't put it in quotes. Though its nice to get a response on this. I'll try 'updating' of sorts and seeing what follows through.

**Comment by BurgerMeister777** [comment]
So it worked like a charm now. Thank you! A lot easier than I thought it'd be once the recent commit got implemented.
