### ISSUE TITLE
Clickteam Fusion 2.5 game: Only some images dump

### ISSUE THREAD

**Issue by Aposke** [LAK132/SourceExplorer#63]
[CrashLog-2021-09-11-20-17.txt](https://github.com/LAK132/SourceExplorer/files/7148328/CrashLog-2021-09-11-20-17.txt)
# IMPORTANT
Please provide a copy of the Error Log (File -> Save Error Log...) or the Crash Log ("SEND-THIS-CRASH-LOG-TO-LAK132.txt") uploaded to https://pastebin.com . Without this we cannot/will not help you! 

**Describe the bug**
SourceExplorer throws the following error as the game exe is loaded:

> | : | : | : WARNING (D:\Repos\SourceExplorer\src\explorer.cpp:1674): Guess MODE1 Failed To Inflate:
| : | : | : | D:\Repos\SourceExplorer\src\explorer.cpp:1133: Inflate Failed: Failed To Inflate (Out of data)
| : | ERROR (D:\Repos\SourceExplorer\src\explorer.cpp:4263): Failed To Read Item 0x289 Of 0x6D1:
| : | : D:\Repos\SourceExplorer\src\explorer.cpp:4051: assign failed

However, the game is then loaded, but only until partway through the image bank, when SourceExplorer stops recognizing the images (and everything that follows) correctly, instead showing the remaining images as 0 bytes in size.

**To Reproduce**
If you want, I can send you the .exe I used via PM. Recreating the bug is done by simply loading the exe into SourceExplorer.

**Additional context**
This might be a version of #43, but the game in question came out before 2.5+, so it might be something different.

**Comment by LAK132** [comment]
Please try the latest version (v2.0.15 or newer)

**Comment by Aposke** [comment]
> Please try the latest version (v2.0.15 or newer)

Tried on 2.0.15, getting a different error now:

> | : | : | : WARNING (../src/explorer.cpp:1926): Guess MODE1 Failed To Inflate:
| : | : | : | ../src/explorer.cpp:1410: Inflate Failed: Failed To Inflate (Out of data)
| : | : | WARNING (../src/explorer.cpp:1926): Guess MODE1 Failed To Inflate:
| : | : | : ../src/explorer.cpp:1410: Inflate Failed: Failed To Inflate (Out of data)
| : | ERROR (../src/explorer.cpp:4636): Failed To Read Item 0x289 Of 0x6D1:
| : | : ../src/explorer.cpp:4321: assign failed
| : | ERROR (../src/explorer.cpp:4636):
| : | : ../src/explorer.cpp:4636: image::bank_t::read
| : | : | ../src/explorer.cpp:4321: assign failed
| : | ERROR (../src/explorer.cpp:4636): Failed To Read Item 0x28A Of 0x6D1:
| : | : ../src/explorer.cpp:4321: assign failed
| : | ERROR (../src/explorer.cpp:4636):
| : | : ../src/explorer.cpp:4636: image::bank_t::read
| : | : | ../src/explorer.cpp:4321: assign failed
| : | ERROR (../src/explorer.cpp:4636): Failed To Read Item 0x28B Of 0x6D1:
| : | : ../src/explorer.cpp:4321: assign failed
| : | ERROR (../src/explorer.cpp:4636):
| : | : ../src/explorer.cpp:4636: image::bank_t::read
| : | : | ../src/explorer.cpp:4321: assign failed
| : | ERROR (../src/explorer.cpp:4636): Failed To Read Item 0x28C Of 0x6D1:
| : | : ../src/explorer.cpp:4321: assign failed
ERROR (../src/dump.cpp:846): AttemptExe failed:
| ../src/dump.cpp:91: OpenGame
| : ../src/explorer.cpp:115: LoadGame: while parsing PE header at: 0x64F3C0
| : ../src/explorer.cpp:5175: header_t::read
| : ../src/explorer.cpp:4636: image::bank_t::read
| : ../src/explorer.cpp:4321: assign failed

Image extraction still fails partway through. Full error log is attached to this message
[error_log_2022_02_19.txt](https://github.com/LAK132/SourceExplorer/files/8102949/error_log_2022_02_19.txt)
