### ISSUE TITLE
Back Button Crashing

### ISSUE THREAD

**Issue by Mech13** [LAK132/SourceExplorer#7]
I was going to search for a path name, the back button crash happens every time I press it under any tab.
It takes around 2-4 seconds then just closes.
I just pressed the top left button of the popup, nothing else. I do have Discord, CTF, Blender, and YT running in the background though.

**Comment by LAK132** [comment]
Could this be related to #8?

**Comment by LAK132** [comment]
Assuming this was fixed at some point. If you're still having trouble please reopen the ticket
