### ISSUE TITLE
Dump Sorted Images not working

### ISSUE THREAD

**Issue by Rainer726** [LAK132/SourceExplorer#71]
[FNaF World Simulator Demo Crash](https://github.com/LAK132/SourceExplorer/files/7739682/SEND-THIS-CRASH-LOG-TO-LAK132.FNAF.WORLD.SIMULATOR.DEMO.txt)
[After Freddy's 3 Crash](https://github.com/LAK132/SourceExplorer/files/7739683/SEND-THIS-CRASH-LOG-TO-LAK132.AFTER.FREDDYS.3.txt)

**Describe the bug**
Basically dumping sorted images is broken, in the fnaf world demo it stopped in the beggining, and in After Freddy's 3 it go at least at 13%

**Comment by LAK132** [comment]
Should be fixed in v2.0.15
