### ISSUE TITLE
source explorer sorted images problem

### ISSUE THREAD

**Issue by NicholasKlak** [LAK132/SourceExplorer#74]
Source Explorer v2.0.13/older versions
ERROR (D:\Repos\SourceExplorer\src\dump.cpp:224): No Object Bank
| WARNING (D:\Repos\SourceExplorer\src\explorer.cpp:1674): Guess MODE1 Failed To Inflate:
| : D:\Repos\SourceExplorer\src\explorer.cpp:1133: Inflate Failed: Failed To Inflate (Corrupt stream)
| WARNING (D:\Repos\SourceExplorer\src\explorer.cpp:1674): Guess MODE1 Failed To Inflate:
| : D:\Repos\SourceExplorer\src\explorer.cpp:1133: Inflate Failed: Failed To Inflate (Corrupt stream)
| WARNING (D:\Repos\SourceExplorer\src\explorer.cpp:1674): Guess MODE1 Failed To Inflate:
| : D:\Repos\SourceExplorer\src\explorer.cpp:1133: Inflate Failed: Failed To Inflate (Corrupt stream)
| WARNING (D:\Repos\SourceExplorer\src\explorer.cpp:1674): Guess MODE1 Failed To Inflate:
| : D:\Repos\SourceExplorer\src\explorer.cpp:1133: Inflate Failed: Failed To Inflate (Corrupt stream)
| WARNING (D:\Repos\SourceExplorer\src\explorer.cpp:1674): Guess MODE1 Failed To Inflate:
| : D:\Repos\SourceExplorer\src\explorer.cpp:1133: Inflate Failed: Failed To Inflate (Corrupt stream)
ERROR (D:\Repos\SourceExplorer\src\dump.cpp:224): No Object Bank

**Comment by LAK132** [comment]
Please attach the entire log file
