### ISSUE TITLE
crash on fnaf1 with  sourcexplorer version 2.0.13

### ISSUE THREAD

**Issue by whynotll83** [LAK132/SourceExplorer#76]
I dragged the FiveNightsatFreddys.exe into the program and it exported 5 textures and crashed.
I'm using v2.0.13-x86-64

[SEND-THIS-CRASH-LOG-TO-LAK132.txt](https://github.com/LAK132/SourceExplorer/files/7834633/SEND-THIS-CRASH-LOG-TO-LAK132.txt)
The side console thing said
"Source Explorer x86_64 v2.0.13-37c6d8c
| WARNING (../src/explorer.cpp:4550): 0x8A Bytes Left Over In Image Data
| : ERROR (../src/explorer.cpp:1042): Out Of Data: 0x9C4 Bytes Remaining, Expected 0xA28
FATAL (../src/dump.cpp:316): unwrap failed:
| ../src/explorer.cpp:1042: Out Of Data: 0x9C4 Bytes Remaining, Expected 0xA28
Something went wrong!
Saving crash log to '"C:\\Users\\whyno\\Downloads\\Source-Explorer-v2.0.13-x86-64\\SEND-THIS-CRASH-LOG-TO-LAK132.txt"'.
Please forward the crash log onto the developer so they can attempt to fix the issues that caused this crash."

**Comment by LAK132** [comment]
Should be fixed in v2.0.15
