### ISSUE TITLE
FNAF 3 Crash

### ISSUE THREAD

**Issue by charuse** [LAK132/SourceExplorer#78]
Crash log is too large for Pastebin. [Here is a link](https://drive.google.com/file/d/1yJCL0bB0j4YY1TPfxuwCX1g0auHBqIC4/view?usp=sharing) to it on Google Drive.

**Describe the bug**
Happened when I was decompiling assets from FNAF 3.

**Expected behavior**
Expected to get assets, did not.

**Additional context**
In the folder Source Explorer created, there are 14 unsorted images, all from a counter object. No audio/favicons.
I am using the most recent version of Source Explorer, v2.0.13

**Comment by LAK132** [comment]
Should be fixed in v2.0.15
