### ISSUE TITLE
error when dumping fnaf 1

### ISSUE THREAD

**Issue by jwdjshhd** [LAK132/SourceExplorer#80]
I was trying to dump fnaf 1 and near the end it crashed and this is the crash log
[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/7937960/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)

**Comment by jwdjshhd** [comment]
i turned off debug and it didnt crash  but the dumping status disappeared and idk where all the stuff it dumps goes

**Comment by jwdjshhd** [comment]
i turned off debug mode and it worked

**Comment by LAK132** [comment]
Did you type CTRL+C in the console by accident, by chance?

**Comment by jwdjshhd** [comment]
not sure i was watching youtube so i might of
