### ISSUE TITLE
Audio Inflate Failure

### ISSUE THREAD

**Issue by Jojomasque** [LAK132/SourceExplorer#85]
Hello, thank you for creating SourceExplorer, it's a very useful tool for me and I thank you for imagining it! I wanted to contact you because I am having some problems. I'm trying to recover the files of Fives Shows at Wario's:Director's Cut but there are several problems.
1:I don't have any images coming out.
2:Some of the music files are corrupted, they have Japanese signs in their names and can't open.
3:The transfer stops at 25%, I tried on three different computers, one not very powerful, one normal and one very powerful and it did not work.
To reproduce the bug, just drag Fives Shows at Wario's:Director's Cut into SourceExplorer.
![Capture d’écran 2022-02-27 160522](https://user-images.githubusercontent.com/100524089/155887783-d73fc452-ce8e-468a-9174-695456a5db0a.png)
[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/8148861/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)
![Capture d’écran 2022-02-27 160732](https://user-images.githubusercontent.com/100524089/155887889-bc0f4a94-1bf6-454e-bd76-95b17026ca42.png)
I would like, if it is possible, that the transfer is done to 100%.  After that, it would be possible to access the images and lastly the corrupted audio files, but the priority is the transfer.The last two problems are also present in the other Fives Nights at Wario's (from Wwwwario), if you want, you can do it but it's really if you don't mind. Thanks in advance and don't hesitate to contact me to explain the progress!

Fives Shows at Wario's Director's Cut(be carreful, it's not the link with base game):  https://gamejolt.com/games/fsaw/562722

**Comment by LAK132** [comment]
Should be fixed in v2.1.2
