### ISSUE TITLE
When trying to open source explorer it does this...

### ISSUE THREAD

**Issue by Hayden5826** [LAK132/SourceExplorer#86]
![uhhh](https://user-images.githubusercontent.com/100655682/156092741-fcf9960c-7884-4003-b52e-59dd6acbff21.png)

I have used Source Explorer on my previous computer and it worked fine. However when trying to use it on my new computer this happens and I have no clue why but I can only assume its a bug or some issue on my end. It would be greatly appreciated if I could just have it fixed somehow :)

**Comment by Hayden5826** [comment]
Sorry if this is the wrong place to post something like this.

**Comment by JakizonX** [comment]
Yeah I got the exact same problem, I've been trying to find solutions to this but there's nothing besides this page.
Everything was perfectly fine until when I reinstalled windows, redownloaded source explorer and was greeted with that weird mess.
![Screenshot 2023-12-28 161531](https://github.com/LAK132/SourceExplorer/assets/152223430/f71dea11-692f-464a-9b71-bd2592526ec4)

**Comment by LAK132** [comment]
Can you try launching it with the `--nogl` flag? Should be something like `C:\path\to\srcexp.exe --nogl` in command prompt

**Comment by JakizonX** [comment]
Seems that it's not a thing on my pc
![image](https://github.com/LAK132/SourceExplorer/assets/152223430/0490fe50-3ad0-456d-a1ff-95be02f46a97)

**Comment by LAK132** [comment]
Please try again with a newer version of SE, v2.1.2 is rather old now (latest is v2.2.0)

**Comment by LAK132** [comment]
It looks like in v2.1.2 the argument was `-nogl`, it was changed to `--nogl` some time after that.

**Comment by JakizonX** [comment]
Huh, I swear I thought I installed 2.2.0 last day, didn't realize I was using an outdated one
I'll check it out now

**Comment by JakizonX** [comment]
Okay everything seems to be working perfectly fine now, I appreciate your help
![image](https://github.com/LAK132/SourceExplorer/assets/152223430/4ccf0207-8568-4b86-a99e-4982829d2109)
