### ISSUE TITLE
bug when fnaf ultimate edition dump

### ISSUE THREAD

**Issue by KKLUCCA** [LAK132/SourceExplorer#88]
when i try to extract fnaf Ultimate Edition 3 i only get audios,when i try to extract fnaf ultimate edition deluxe the apliccation crashes, the same happens with fnaf ultimate edition 
[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/8192951/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)

**Comment by LAK132** [comment]
Fixed in fa18a842395823924b30bac5aad5eb267d3c6f67 (v2.0.17)
