### ISSUE TITLE
Fnas Maniac Mania Recoded : Exporting images or viewing them via the image bank crashes the program

### ISSUE THREAD

**Issue by DeceptedPar** [LAK132/SourceExplorer#89]
# IMPORTANT
Please provide a copy of the Error Log (File -> Save Error Log...) or the Crash Log ("ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt"). Without this we cannot not help you!

https://github.com/LAK132/SourceExplorer/files/8274866/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt

**Describe the bug**
I tried to export image files or try to dump image files from FNAS mania mania recoded and it just... crashes

**To Reproduce**
1. Load up SourceExplorer and load up FNAS Maniac Mania Recoded
2. Click on 'Dump images' or goto image bank and press 'view image'
3. Then you see the error

**Expected behavior**
I either expected the images to dump or to view the image

**Screenshots**
I dont know how screenshots would help here

**Additional context**
I dont have any extra information

**Comment by DeceptedPar** [comment]
also Hi LAK, I got a new pc from the last time we talked (the previous issue I committed here) and I can finally compile the builds now

**Comment by megasaturn** [comment]
why would you decompile fnas mm recoded?

**Comment by DeceptedPar** [comment]
to get the textures but trying to decompile the textures when it did work never got the texture so this time I thought of trying to just dump the images and it crashed

**Comment by DeceptedPar** [comment]
also when trying to get the images NO IMAGES get exported, it may be the program itself but... i dont know

**Comment by LAK132** [comment]
Fixed in fa18a842395823924b30bac5aad5eb267d3c6f67 (v2.0.17)
