### ISSUE TITLE
Assets.dat support?

### ISSUE THREAD

**Issue by CelestialAmber** [LAK132/SourceExplorer#9]
Would it be possible to add support for Clickteam games that use Assets.dat files for assets? (Baba is You, Freedom Planet, AVGN Adventures)

These tools would be a good reference for on how to potentially be able to do it (Baba is You's Assets.dat isn't compatible with the tool, probably because it's made in MMF2)
https://github.com/snickerbockers/fp-assets
https://github.com/snickerbockers/freedom_editor

**Comment by LAK132** [comment]
I haven't seen FP or AVGN but it looks like MP2 ported Baba Is You from Fusion to Chowdren, most likely using their Anaconda/Chowdren tool. Source Explorer is only based on Anaconda and knows nothing about the Chowdren engine, so it's highly unlikely that SE will ever be able to open these games.
