### ISSUE TITLE
Unexpected error on extracting or unwrapping images from this game.

### ISSUE THREAD

**Issue by DerpyMario** [LAK132/SourceExplorer#90]
![errorcase](https://user-images.githubusercontent.com/88537784/159217718-74e259db-6151-4ab4-827a-99b236a17088.PNG)

[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/8313630/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)

It's from this sonic.exe fangame (which assumed to be a ROM hack) that came from the gamejolt site. Had to extract images but this happened....

**Comment by LAK132** [comment]
Fixed in fa18a842395823924b30bac5aad5eb267d3c6f67 (v2.0.17)
