### ISSUE TITLE
Unable to dump A Night at The Restaurant indefinitely

### ISSUE THREAD

**Issue by adncroz** [LAK132/SourceExplorer#92]
_Please provide a copy of the Error Log (File -> Save Error Log...) or the Crash Log ("ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt"). Without this we cannot not help you!_
![ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/8358174/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)

**Describe the bug**
_A clear and concise description of what the bug is._
Upon opening the the EXE file of the game, the command prompt window will announce a fatal error impeding the creation of any folder or file (see Screenshots.)

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to File, "Open and Dump...", select ANightAtTheRestaurant.exe/drag the EXE file to the Source Explorer window.
2. It doesn't matter if Auto-Dump Mode is enabled or not. By having completed Step 1, the error will trigger.
4. See error.

**Expected behavior**
_A clear and concise description of what you expected to happen._
I expected a folder to generate, even if empty. My intention was to extract both sound and image files.

**Screenshots**
_If applicable, add screenshots to help explain your problem._
![FATAL](https://user-images.githubusercontent.com/102481442/160294474-f3c35b1e-9b3a-4d3e-a9e1-05e892b45dc2.png)

**Additional context**
_Add any other context about the problem here._
I am not completely sure if the game's engine is Clickteam 2.5+. There are two versions of the game; neither 1.0.0 nor 1.1.0 work.
GAME: https://gamejolt.com/games/a_night_at_the_restaurant/699227
DIRECT DOWLOADS: [v1.0.0](https://drive.google.com/file/d/1QlAj4bg1LYJHRbfX2Ygyu4K6z7SnGkuJ/view?usp=sharing), [v1.1.0](https://drive.google.com/file/d/1XRM0XNcLmsU1bzQDnpJQLNJdzJ1po11m/view?usp=sharing).

EDIT 28/3/2022: new version 1.1.1 does not work either. Direct download, anyways: [v1.1.1](https://drive.google.com/file/d/1YJvyvxDSNYkTG3H0kbxto1KpzNK8qaxb/view?usp=sharing)

**Comment by LAK132** [comment]
You will need to open the `.dat` instead of the `.exe`
