### ISSUE TITLE
Invalid Padding

### ISSUE THREAD

**Issue by MostafaSaad1987** [LAK132/SourceExplorer#93]
# IMPORTANT
Copy of the Error Logs:
[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/8362700/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)
[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/8362753/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)

**Describe the bug**
Sprites/Images don't decompile in a lot of games, mostly recent-ish games, using recent versions of the newest Clickteam Fusion version(s).
Attached are the latest error reports for the last 2 games I tried to decompile.

**To Reproduce**
1. Try to decompile Ultra Custom Night or Baby's Nightmare Circus 2.
2. See errors.
3. Everything decompiles beside images, leaving the images folder empty.

**Expected behavior**
Everything gets decompiled.

**Screenshots**
![Screenshot 2022-03-28 144631](https://user-images.githubusercontent.com/52860974/160401116-d777dc5c-5214-4906-ab6b-c52537b64c85.jpg)

**Additional context**
Links for the games: 
https://gamejolt.com/games/ultracustomnight/497721
https://gamejolt.com/games/thethirdsecondone/557231

**Comment by Mosquitobrain** [comment]
Similar issue here
[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/8393891/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)
 Debug console says "| : | FATAL (../src/explorer.cpp:730): Assertion 'colors.size() * 2 == RGB.size()' failed: '0x5100' != '0x2880'"

**Comment by ArmagdoGaming** [comment]
Yeah, it still doesn't work. Used both 2.0.17 and 2.1.0, both give the same error messages (Corrupt Stream, Invalid Type Detected, and Failed To Inflate).
Attached is the error log from 2.1.0 error.

Copy of the Error Logs:
[ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt](https://github.com/LAK132/SourceExplorer/files/8526892/ATTACH-TO-ISSUE-ON-SOURCE-EXPLORER-GITHUB-REPO.txt)

Screenshots
![Screenshot 2022-04-21 045448](https://user-images.githubusercontent.com/52860974/164362713-70ed8c87-61b8-4b9b-8452-579b8dc169a7.jpg)

**Comment by LAK132** [comment]
Oh that's the 2.5+ sorted image dumps problem. That's a known issue.
