### ISSUE TITLE
No Image dumped. 

### ISSUE THREAD

**Issue by itapir** [LAK132/SourceExplorer#94]
Hi. Thanks for your software. I used it to dump a Japanese game. It worked like a charm on dumping the sounds. However no image was dumped. Here's the console window:
| : | : WARNING (../src/explorer.cpp:1690): Invalid Type Detected (0x225D)
| : | : WARNING (../src/explorer.cpp:1690): Invalid Type Detected (0x225C)
| : WARNING (../src/explorer.cpp:2053): Guess MODE1 Failed To Inflate:
| : | ../src/explorer.cpp:1464: Inflate Failed: Failed To Inflate (Corrupt stream)

I tried pastebin but the error log was like 30MB and I failed to paste it on pastebin. I uploaded it on MEGA:
https://mega.nz/file/dp913CZS#XL9-0M-dkZgRTXMdtk9pJNwt4pVllVdjR-SbOsJWzMM
Also the game exe file:
https://mega.nz/file/55sFAJ5C#KJmQJs_ANd5L2eHX3Lh2295wwn8xSLCuKzoIijaL56M

btw, it's nsfw ;^)

**Comment by LAK132** [comment]
Should be fixed in v2.1.2
